---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install neofetch
    apt:
      name: neofetch
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: remove something else
    apt:
      name: something else
      state: absent
    when: ansible_distribution == "Ubuntu"
