---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu_servers
  become: true
  tasks:

  - name: Install cmatrix
    tags: cmatrix,ubuntu
    apt:
      name:
        - cmatrix
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Copy Files
    tags: poop,files,ubuntu
    copy:
      src: poop.txt
      dest: /home/damon/Desktop/poop.txt
      owner: damon
      group: damon
      mode: 0644

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: Install Terraform
    tags: terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.2.2/terraform_1.2.2_linux_amd64.zip
      dest: /home/damon/Desktop/terraform
      remote_src: yes
      owner: root
      group: root
      mode: 0755

  - name: Copy Files
    tags: poop,files,ubuntu
    copy:
      src: poop.txt
      dest: /home/damon/Desktop/poop.txt
      owner: damon
      group: damon
      mode: 0644

- hosts: ubuntu_servers
  become: true
  tasks:

  - name: Modifying foods.conf file
    tags: files
    lineinfile:
      path: /home/damon/Desktop/terraform/foods.conf
      regexp: '^a ='
      line: a = anchovies
    when: ansible_distribution == "Ubuntu"
